### ISSUE TITLE
Open all outgoing links on a new tab 

### ISSUE THREAD

**Issue by DininduSenanayake** [nesi/support-docs#219]
* Some pages have a number of outgoing links from application GH repo to external support docs to Youtube links. Existing implementation opens all of these links on the current tab which can be a bit distracting

**Solution**

If we are to change this behaviour which is to open all outgoing links on a new tab, It can be done by adding the `mkdocs-open-in-new-tab` to the workflow and then add `open-in-new-tab` plugin to `mkdocs.yml` 

```bash
plugins: 
  - open-in-new-tab
```

**Comment by CallumWalley** [comment]
I'm fine with this.
Can be considered bad practice, but I think for external links that is the desired behavior most of the time.

Could also be done on a per-link basis with `{:target="_blank"}`

**Comment by CallumWalley** [comment]
Done in #220
