### ISSUE TITLE
Receiving User Feedback

### ISSUE THREAD

**Issue by jennan** [nesi/support-docs#277]
There is already a ‘edit this page’ button, but we would like a method of leaving feedback in a slightly less confronting way.

Could add a button to automatically open an issue on github and/or a link to send an email with prefilled title?

**Ported from internal Jira ticket https://nznesi.atlassian.net/browse/SD-256**

**Comment by CallumWalley** [comment]
Custom button. Made with love.
<path d="m 240,-880 c -21.9999,0 -40.81777,7.84904 -56.48438,23.51562 C 167.84905,-840.81778 160,-821.9999 160,-800 v 640 c 0,21.9999 7.84905,40.81778 23.51562,56.48438 C 199.18223,-87.849042 218.0001,-80 240,-80 h 240 v -80 H 240 v -640 h 280 v 200 h 200 v 80 h 80 V -640 L 560,-880 Z m 657.1875,415.46875 c -2.75579,-0.0432 -5.50262,0.17595 -8.20312,0.625 H 580.3125 c -25.7671,-1.22558 -44.5544,26.06504 -40,50.15625 v 349.84375 l 80,-80 c 96.07413,-0.46452 192.26356,0.9488 288.28125,-0.70313 28.10555,-5.07873 35.41265,-36.67738 31.71875,-60.9375 -0.40074,-75.53522 0.9163,-151.16192 -0.70312,-226.64062 -3.61101,-19.95943 -23.13139,-32.04114 -42.42188,-32.34375 z m -286.28906,66.71875 h 257.61718 v 192.26562 l -247.45439,0.16918 -10.16279,9.45274 z" />
