### ISSUE TITLE
Missing space breaks version selection

### ISSUE THREAD

**Issue by ndjones** [nesi/support-docs#351]
The concatenation of conditional `<button .. class="` tags doesn't add spaces between tags. in at least one context this joins tags and breaks button selection.

The example showing this is on the Singularity app as selected here:
https://docs.nesi.org.nz/Scientific_Computing/Supported_Applications/?search=docker
Once the page has loaded (wait, its a slow to resolve the filter) then select the Singularity app. Note that the Warning box doesn't have any content. 
The warning is from this line of code - it appears from the code like its meant to set `class="md-tag-ver-shown"` in order to select the default version button but that class value is joined on to the following value. 
If you click on the default version 3.11.3 this adds an additional `class="md-tag-ver-shown"` to the button and therefore displays the intended Warning message.

Suggested fix - add a space after each tag value to ensure there is always a space.

https://github.com/nesi/support-docs/blob/76e84b863d0b49cc7061247c2fe16c997f1b4cdd/overrides/partials/app/app_version.html#L13

**Comment by CallumWalley** [comment]
Good catch!
