### ISSUE TITLE
Alphabetic sort of Supported Applications is case sensitive

### ISSUE THREAD

**Issue by ndjones** [nesi/support-docs#362]
**Describe the bug**
The list of supported applications shows capitalised applications first, then followed by lower case applications. these means the names aren't merged into a sort by letter, there are two lists one starting with capitals, one starting with lower case.

**Link to page displaying bug**
It looks like its coming from the automated module list page, so is perhaps an artefact of how this is generated: https://github.com/nesi/modules-list/blob/main/module-list.json

**Expected behavior**
A single case insensitive list of applications alpha sorted

**Comment by CallumWalley** [comment]
Fixed in https://github.com/nesi/modules-list/commit/37b92f662a006d1e0354956f523f1c54d078a060

**Comment by ndjones** [comment]
thanks, looks good 👍
